FROM golang:1.24 AS builder
WORKDIR /app
COPY go.mod ./
RUN go mod tidy
COPY . .
RUN go build -o gateway ./cmd

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/gateway .
EXPOSE 8088
CMD ["./gateway"]
