/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/attendance-list-student`; params?: Router.UnknownInputParams; } | { pathname: `/attendance-list`; params?: Router.UnknownInputParams; } | { pathname: `/courses`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login-student`; params?: Router.UnknownInputParams; } | { pathname: `/login-teacher`; params?: Router.UnknownInputParams; } | { pathname: `/role-select`; params?: Router.UnknownInputParams; } | { pathname: `/student-courses`; params?: Router.UnknownInputParams; } | { pathname: `/student-view`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/.expo/types/router.d`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/attendance-list-student`; params?: Router.UnknownOutputParams; } | { pathname: `/attendance-list`; params?: Router.UnknownOutputParams; } | { pathname: `/courses`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login-student`; params?: Router.UnknownOutputParams; } | { pathname: `/login-teacher`; params?: Router.UnknownOutputParams; } | { pathname: `/role-select`; params?: Router.UnknownOutputParams; } | { pathname: `/student-courses`; params?: Router.UnknownOutputParams; } | { pathname: `/student-view`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/.expo/types/router.d`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/attendance-list-student${`?${string}` | `#${string}` | ''}` | `/attendance-list${`?${string}` | `#${string}` | ''}` | `/courses${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login-student${`?${string}` | `#${string}` | ''}` | `/login-teacher${`?${string}` | `#${string}` | ''}` | `/role-select${`?${string}` | `#${string}` | ''}` | `/student-courses${`?${string}` | `#${string}` | ''}` | `/student-view${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/.expo/types/router.d${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/attendance-list-student`; params?: Router.UnknownInputParams; } | { pathname: `/attendance-list`; params?: Router.UnknownInputParams; } | { pathname: `/courses`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login-student`; params?: Router.UnknownInputParams; } | { pathname: `/login-teacher`; params?: Router.UnknownInputParams; } | { pathname: `/role-select`; params?: Router.UnknownInputParams; } | { pathname: `/student-courses`; params?: Router.UnknownInputParams; } | { pathname: `/student-view`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/.expo/types/router.d`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
