version: '3'

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - mysqr-network

  student:
    build: ./student
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.student.rule=PathPrefix(`/api/scan`)"
      - "traefik.http.services.student.loadbalancer.server.port=8082"
    networks:
      - mysqr-network

  teacher:
    build: ./teacher
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teacher.rule=PathPrefix(`/api/classes`)"
      - "traefik.http.services.teacher.loadbalancer.server.port=8081"
    networks:
      - mysqr-network

  qr:
    build: ./qr
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qr.rule=PathPrefix(`/api/qr`)"
      - "traefik.http.services.qr.loadbalancer.server.port=8080"
    networks:
      - mysqr-network

  database:
    build: ./database
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.database.rule=PathPrefix(`/api/db`)"
      - "traefik.http.services.database.loadbalancer.server.port=8084"
    networks:
      - mysqr-network

networks:
  mysqr-network:
    driver: bridge 